open-falcon/falcon-plus

common/pool/pool.go
modules/api/app/controller/graph/graph_controller.go
modules/api/main.go

修正 import 路徑

---

Makefile
common/logruslog/logruslog.go
common/pflag/cmd_util.go
common/vipercfg/sample-config.json
common/vipercfg/vipercfg.go
common/vipercfg/vipercfg_test.go
config/alarm.json
config/api.json
config/graph.json
g/g.go
modules/api/app/controller/strategy/strategy_controller.go
modules/api/cfg.json.example
scripts/mysql/db_schema/alarms-db-schema.sql

* Fixed missing static files/folder path issue
1. fixed missing static files/folder path issue of alarm & graph
* Add alarm module
1. move alarm module into falcon_plus
2. create db script for create tables, those table for support alarm module to save triggered alerts history
3. modified build files

Add alarm module  & fixed some static files error

---

modules/api/app/controller/graph/graph_controller.go

front end change: https://github.com/open-falcon/dashboard/pull/25

refine endpoint_counter query api

---

README.md
fix_gosrouce_fetch_error.sh

加上脚本协助使用者解决无法抓取 "golang.org/x/" 的问题

add a script to help resolve fetach error on "golang.org/x/*"

---

modules/api/app/controller/graph/grafana_controller.go
modules/api/config/database.go

* 增进db connect失败的提示讯息
* 修复grafana只能绘图单一线图的问题

fixed multiple target rendering issue on grafana api

---

modules/api/app/controller/expression/expression_controller.go

修复问题回报:
https://github.com/open-falcon/falcon-plus/issues/56

fix wrong action id fetch issue

---

modules/api/app/controller/alarm/alarm_events_controller.go
modules/api/app/controller/host/hostgroup_controller.go
modules/api/app/controller/template/template_controller.go
modules/api/app/model/falcon_portal/grp_tpl.go

* fix bugs of wrong bind user
* fix missing right tag of validation
* add delete grp_tpl to clean related records when template is deleted
* update binding struct of APIGetAlarmListsInputs

[api] fix bugs and missing codes

---

Makefile

as title 
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

refactor: show gofmt diff data.

---

Makefile
common/backend_pool/rpc_backends.go
modules/gateway/g/logger.go
modules/gateway/main.go
modules/gateway/sender/send_tasks.go
modules/gateway/sender/sender.go
modules/graph/http/http.go
modules/transfer/receiver/rpc/rpc.go

https://github.com/open-falcon/falcon-plus/pull/79

[bugfix] gateway cannot work because of wrong rpc codec

---

config/api.json
modules/api/app/controller/uic/user_controller.go
modules/api/cfg.example.json

基于 https://github.com/open-falcon/falcon-plus/issues/85 的问题
加上可以让管理者停用注册的功能

supprot disable singup by config

---

Makefile
common/backend_pool/tsdb_backends.go
modules/api/app/controller/uic/user_controller.go
modules/api/test/api/team/team_test.go
modules/graph/index/index_update_all_task.go
modules/graph/main.go

* don't use generic names such as "this" or "self"
* fix go vet errors
* fix some typos.
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

fix go vet error and some typos.

---

modules/api/app/controller/uic/user_controller.go
modules/api/app/helper/session.go

fixed problem when signup disalbed, then create user by admin will broken.
管理者创建使用者
关闭对外的注册功能
非管理者强制建立使用者

fixed problem on create user by admin broken

---

.travis.yml
Makefile

feat: add check misspell-check command

---

modules/alarm/api/uic.go
modules/alarm/cron/combiner.go
modules/alarm/cron/event_consumer.go
modules/alarm/cron/model.go
modules/alarm/main.go

https://github.com/open-falcon/falcon-plus/issues/128

[alarm]fix: im-sending not work in some particular cases.

---

modules/hbs/cache/agents.go
modules/hbs/cache/cache.go
modules/hbs/cache/expressions.go
modules/hbs/cache/groups.go
modules/hbs/cache/hosts.go
modules/hbs/cache/plugins.go
modules/hbs/cache/strategies.go
modules/hbs/cache/templates.go
modules/hbs/db/agent.go
modules/hbs/db/db.go
modules/hbs/db/expression.go
modules/hbs/db/group.go
modules/hbs/db/host.go
modules/hbs/db/plugin.go
modules/hbs/db/strategy.go
modules/hbs/db/template.go
modules/hbs/g/cfg.go
modules/hbs/g/g.go
modules/hbs/http/common.go
modules/hbs/http/http.go
modules/hbs/http/proc.go
modules/hbs/main.go
modules/hbs/rpc/agent.go
modules/hbs/rpc/hbs.go
modules/hbs/rpc/rpc.go

Reverts open-falcon/falcon-plus#95

Revert, use NOTICE file

---

modules/api/app/controller/dashboard_graph/dashboard_graph_controller.go
modules/api/app/controller/template/template_controller.go

https://github.com/open-falcon/falcon-plus/issues/109

[api] fix 'record not found' when clone screen or add graph.

---

modules/graph/http/common.go
modules/graph/http/proc.go

https://github.com/open-falcon/falcon-plus/pull/143
https://github.com/open-falcon/falcon-plus/issues/104

[graph] self-monitoring compatible with anteye and task.

---

cmd/start.go
modules/agent/cron/collector.go
modules/graph/cron/clean.go
modules/graph/rrdtool/sync_disk.go

我看falcon中的ticker退出循环时有的会Stop有的不会Stop，所以搜索了一下让代码更一致

Add ticker.Stop for all ticker when quit

---

config/hbs.json
modules/hbs/cache/agents.go
modules/hbs/db/db.go
modules/hbs/g/cfg.go

增加最大连接数配置防止极端情况无限创建连接拖垮数据库
host表只有需要insert或者update的时候才去更新数据库，减少数据库访问。
https://github.com/open-falcon/falcon-plus/issues/183

增加数据库最大连接数配制，减少数据库访问

---

g/tool.go
modules/aggregator/cron/query.go
modules/aggregator/cron/run.go

-Optimize part of the code

---

docs/_posts/HostGroup/2017-08-22-hostgroup_update_partial_hosts.md
modules/api/app/controller/host/host_routes.go
modules/api/app/controller/host/hostgroup_controller.go
modules/api/app/model/falcon_portal/grp_host.go

新增一个 API 用于批量绑定和删除 hostgroup 中的 host
#209

[api] add new api to update partial hosts in grp_host

---

modules/api/app/controller/strategy/strategy_controller.go

fix right value on update strategy

---

docs/_posts/2017-01-01-authentication.md
docs/_posts/Graph/2017-01-01-grafana.md

fix doc typo of sesion auth api & add grafana api doc

---

vendor/github.com/toolkits/sys/cmd.go
vendor/vendor.json

https://github.com/open-falcon/falcon-plus/issues/77

[bugfix]fix setpgid of plugin in vendor which is missing last time

---

modules/agent/g/rpc.go

fix this bug：
https://github.com/open-falcon/falcon-plus/issues/290

[agent]Fixed an issue where errors were not returned after rpc timed out.

---

modules/agent/funcs/diskstats.go

diskstats add flash device support.

flash device

---

README.md

现在readme中的logs的路径是$WorkDir/$moduleName/log/logs/xxx.log
正确logs的路径是$WorkDir/$moduleName/logs/xxx.log

update the logs path

---

modules/api/app/controller/expression/expression_controller.go

https://github.com/open-falcon/falcon-plus/issues/331

[api] fix right value regex pattern of expression api

---

modules/judge/store/func.go

https://github.com/open-falcon/falcon-plus/issues/346

func为空时会导致judge服务crash

---

modules/hbs/cfg.example.json

caused by pr https://github.com/open-falcon/falcon-plus/pull/185

[hbs] add macConns item to hbs config file

---

modules/api/app/utils/auth_middle.go

Add cross-domain method PATCH

---

modules/api/app/controller/graph/graph_controller.go

Signed-off-by: yul <yul@inke.cn>

优化counter筛选: 支持以 ! 前缀反选counters

---

Makefile

https://github.com/open-falcon/falcon-plus/pull/404

[bugfix]fix plugin dir location in makefile

---

modules/agent/funcs/du.go
modules/agent/funcs/du_test.go

https://github.com/open-falcon/falcon-plus/issues/456

optimize du.bs

---

common/utils/func_test.go
common/utils/md5_test.go
common/utils/objpool.go
common/utils/tags_test.go
modules/agent/funcs/gpu.go
modules/graph/g/utils_test.go
modules/graph/rrdtool/utils.go

+// Copyright 2017 Xiaomi, Inc.
+//
+// Licensed under the Apache License, Version 2.0 (the "License");
+// you may not use this file except in compliance with the License.
+// You may obtain a copy of the License at
+//
+//     http://www.apache.org/licenses/LICENSE-2.0
+//
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.

规范开源信息，添加Copyright

---

modules/api/app/controller/host/plugins_controller.go

APICreatePluginInput DirPaht field rename

APICreatePluginInput DirPaht field rename

---

docs/_posts/Template/2017-01-01-tpl_create.md
modules/api/app/controller/template/template_controller.go

return new template info on create of template

---

docs/_posts/Aggreator/2017-01-01-aggreator_create.md

fix API document, in fact 'POST' method is used to create aggregator

fix API document, in fact 'POST' method is used to create aggregator

---

docker/README.md

Add git clone parameter "--depth=1" to reduce clone time

Reduce git clone time

---

modules/api/app/controller/expression/expression_controller.go

https://github.com/open-falcon/falcon-plus/issues/331 follow up.

[api] fix right value regex pattern of expression update api 

---

modules/agent/funcs/du.go

修复agent中du.go里errors.New忘赋值给err的小问题

---

modules/api/app/controller/graph/grafana_controller.go

a better way to fix https://github.com/open-falcon/falcon-plus/pull/515

fix grafana query endpoint api, use gorm method instead of concat sql

---

docs/doc/aggregator.html

modify doc due to issue 578

---

.dockerignore
Dockerfile
docker/ctrl.sh

and fix metric_list_file to use abs_path.

reduce docker image size

---

vendor/github.com/toolkits/nux/dfstat.go
vendor/github.com/toolkits/nux/dfstat_linux.go
vendor/github.com/toolkits/nux/ifstat.go
vendor/github.com/toolkits/nux/loadavg.go
vendor/github.com/toolkits/nux/meminfo.go
vendor/vendor.json

update toolkits/nux dependce

---

docker/k8s-example/README.md
docker/k8s-example/init_mysql_data.sh
docker/k8s-example/mysql.yaml
docker/k8s-example/openfalcon-dashboard.yaml
docker/k8s-example/openfalcon-plus.yaml
docker/k8s-example/redis.yaml

add k8s example

---

modules/agent/control
modules/aggregator/control
modules/alarm/control
modules/gateway/control
modules/graph/control
modules/hbs/control
modules/judge/control
modules/nodata/control
modules/transfer/control

Fix typos in `/falcon-plus/modules/MODULE_NAME/control`.
> "stoped" -> "stopped"

fix: fix typos

---

modules/alarm/cron/sms_sender.go

fix config url is null.

---

vendor/github.com/toolkits/nux/cpustat.go
vendor/github.com/toolkits/nux/dfstat.go
vendor/github.com/toolkits/nux/iostat.go
vendor/github.com/toolkits/nux/ss_s.go
vendor/vendor.json

this PR fix falcon-agent crash on kernel 4.18+ 
fix issues below:
#770 
#747

[agent] update vendor/github.com/toolkits/nux for kernel 4.18+

---

modules/api/app/controller/dashboard_graph/dashboard_graph_controller.go

https://github.com/open-falcon/falcon-plus/issues/225

修复screen中graph无法取消加和的bug

---

modules/agent/funcs/diskstats.go

Add support Network block device in diskstats
Signed-off-by: XianChaoBo <xianchaobo@bytedance.com>

Add support nbd device in diskstats

---

docker/README.md

1. format doc 
2. fix `git clone`  faild in WSL2 with git-2.17.1

format doc

---

scripts/mysql/db_schema/2_portal-db-schema.sql

Update: change alter_link content text to mediumtext

---

modules/nodata/config/service/host.go

fix: nodata sql injection #951

fix: nodata sql injection
