common/pool/pool.go, modules/agent/g/rpc.go, modules/gateway/sender/conn_pool/conn_pool_rpc.go, modules/transfer/sender/conn_pool/conn_pool_manager.go
Ref https://github.com/golang/go/wiki/Timeouts
Using channel to implement timeout, channel should have a buffer size of 1. Otherwise, the goroutine that has the send channel would never be destroyed.
=> fix goroutine leaks problem when timeout really happens.

docker/owl-light/Dockerfile
update docker build file, `npm install yarn -g` line will cause docker-image build failed
=> update docker file for owl-light

modules/api/app/controller/uic/session_controller.go
目前falcon+ (python版) 和 owl-light的前端页面的登入方式有一点不同.
所以我将这边的api改為两边都可以相容的模式.
=> [api] fix login conflict with new dashboard & owl-light frontend page

modules/api/app/controller/uic/team_controller.go
GetTeamByName没有根据name设置where条件，只会返回team表中最后一个team的users。
=> fix GetTeamByName获取team错误

config/confgen.sh
Avoiding warnings while $UNAME is not set.
=> Fix "unary operator expected"

modules/agent/funcs/portstat.go
1. after checking TCP ports, check UDP ports too
1. a better solution may be adding `tcp.port.listen` and `udp.port.listen` to avoid one port listening both TCP and UDP
=> net.port.listen also check udp port

modules/agent/funcs/dfstat.go, modules/agent/g/const.go
某些挂载点的blocks=0时，UsedPercent = 100.0，使用UserdPercent设置的报警，将会大量误报，该类挂载点可忽略
=> fix(agent): ignore mount point when blocks=0

modules/aggregator/cron/computer.go, modules/aggregator/cron/run.go, modules/aggregator/cron/run_test.go, modules/aggregator/cron/worker.go
1. commit: fe65951    增加5个操作符，例如 分子 $(cpu.busy)>10，分母 $#，则表示cpu.busy>10的机器数量在整个集群的比例，用于评估集群的健康度或机器利用度
2.  commit: e69ca2f    当集群监控配置中step <= 0时，创建ticker会引发panic，现增加判断
=> aggreator增加5个运算符（支持集群监控）

modules/graph/cron/clean.go, modules/graph/g/g.go, modules/graph/g/git.go, modules/graph/index/cache.go, modules/graph/index/index.go, modules/graph/index/index_update_all_task.go, modules/graph/index/index_update_incr_task.go, modules/graph/main.go, modules/graph/rrdtool/rrdtool.go, modules/graph/rrdtool/sync_disk.go, modules/graph/store/history.go, modules/graph/store/store.go
1. commit: 26a128f    graph中使用了GraphItems、HistoryCache缓存队列，随着脏数据积累，内存开销会越来越大，现增加周期性清理工作，有效性参照 IndexedItemCache 缓存队列
2. commit: d9afc26    在一些不规范的使用场景，大量脏数据会被上报（数据不连续，偶尔一两个点），会严重消耗RRD和持久化性能，现增加数据点的数量阀值，只有在超过阀值、或超过一定时间（保护性）、或进程退出时强制持久化存储
=> graph缓存队列控制和持久化优化

config/aggregator.json
默认超时配置connect_timeout、request_timeout缺失，导致QueryCounterLast()一直超时
=> 修复aggregator超时的问题

modules/api/app/controller/host/hostgroup_controller.go
=> fix 'equal' error can't bind template to hostgroup

modules/api/app/controller/host/hostgroup_controller.go
There has logical judgment error in hostgroup_controller.go for func DeleteHostGroup, "hostgroup.CreateUser == user.Name" should be "hostgroup.CreateUser != user.Name"
=> fix DeleteHostGroup bug in hostgroup_controller

modules/api/app/controller/graph/grafana_controller.go
比如在Grafana 的Graph视图中，配置了多个查询语句，当其中有一个查询语句没有匹配到的counter时，代码中应该继续counter并继续执行其他的查询语句，不然会导致其他正常的查询语句也无法渲染视图。这个bug，在使用Grafana的JS动态展示Dashboard时，体验会很差。
=> API：修复当grafana graph有多个查询时，因为其中一个未匹配到导致其他正常的查询也无法渲染视图

docs/_posts/Host/2017-01-01-host_maintain.md, docs/_posts/Host/2017-01-01-host_reset.md, modules/api/app/controller/host/host_routes.go, modules/api/app/controller/host/maintain_controller.go, modules/api/app/model/falcon_portal/host.go
=> add maintain/reset api

modules/hbs/db/strategy.go
策略生效时间支持某段时间不执行，例如每天1点到5点不执行就可以写成run_begin: 05:00 run_end: 1:00
https://github.com/open-falcon/falcon-plus/issues/182
=> the execution time can span 24 hours.

docs/_posts/Alarm/2017-01-01-alarm_eventcases_list.md, modules/api/app/controller/alarm/alarm_events_controller.go
通过主机（组）过滤, 会查询出任何发生在endpoints列表里面的报警
"endpoints"":["endpoint1", "endpoint2"]
通过策略查询报警:
"strategy_id": 5
通过模板查询报警:
"templete_id": 5
=> 修改了alarm/eventcases api接口，增加了3个过滤条件

modules/graph/g/utils.go, modules/graph/g/utils_test.go
Sprintf性能太差, RrdFileName、FormRrdCacheKey均为高频使用的函数。
附benchmark
```
=== RUN   Test_RrdFileName
--- PASS: Test_RrdFileName (0.00s)
=== RUN   Test_FormRrdCacheKey
--- PASS: Test_FormRrdCacheKey (0.00s)
goos: darwin
goarch: amd64
pkg: github.com/open-falcon/falcon-plus/modules/graph/g
Benchmark_RrdFileName-4            	10000000	       127 ns/op
Benchmark_RrdFileName_orig-4       	 3000000	       506 ns/op
Benchmark_FormRrdCacheKey-4        	20000000	        90.4 ns/op
Benchmark_FormRrdCacheKey_orig-4   	 5000000	       324 ns/op
PASS
ok  	github.com/open-falcon/falcon-plus/modules/graph/g	7.282s
```
=> change: 优化, 使用"+"代替Sprintf

modules/judge/cron/strategy.go, modules/judge/g/var.go, modules/judge/rpc/receiver.go
=> 优化judge内存使用

modules/api/app/controller/alarm/alarm_events_controller.go
In `modules/api/app/controller/alarm/alarm_events_controller.go`  paginate should be `step` not `page` in sql.
=> [alarm_events_controller]fix AlarmLists paginate api change page to step sql

modules/alarm/cron/callback.go
In the real scene, we need to know the left value of the alarm event. But there is no method to get it.
=> callback returns left_value, that service outside can use it.

common/utils/func.go, common/utils/func_test.go, common/utils/md5.go, common/utils/md5_test.go, common/utils/objpool.go, common/utils/tags.go, common/utils/tags_test.go
优化效果见如下benchmark结果
```
goos: darwin
goarch: amd64
pkg: github.com/n4mine/falcon-plus/common/utils
Benchmark_PK-4                            	 2000000	       632 ns/op	     112 B/op	       4 allocs/op
Benchmark_PK_orig-4                       	 2000000	       702 ns/op	     160 B/op	       7 allocs/op
Benchmark_PK2-4                           	10000000	       126 ns/op	      32 B/op	       1 allocs/op
Benchmark_PK2_orig-4                      	10000000	       204 ns/op	      64 B/op	       3 allocs/op
Benchmark_UUID-4                          	 2000000	       826 ns/op	     128 B/op	       4 allocs/op
Benchmark_UUID_orig-4                     	 2000000	       894 ns/op	     200 B/op	       9 allocs/op
Benchmark_Md5-4                           	 5000000	       294 ns/op	      64 B/op …
```
=> perf: common utils. 包括Md5, PK, PK2, UUID, SortedTags, DictedTagstring等函数

.gitignore, modules/agent/funcs/funcs.go, modules/agent/funcs/gpu.go, vendor/github.com/mindprince/gonvml/LICENSE, vendor/github.com/mindprince/gonvml/Makefile, vendor/github.com/mindprince/gonvml/NVML_NOTICE, vendor/github.com/mindprince/gonvml/README.md, vendor/github.com/mindprince/gonvml/bindings.go, vendor/github.com/mindprince/gonvml/cmd/example/example.go, vendor/github.com/mindprince/gonvml/nvml.h, vendor/vendor.json
=> support gpu monitor

scripts/mysql/db_schema/5_alarms-db-schema.sql
event表主键id字段类型为mediumint，数据默认保存7天。当数据量比较多时，id自增到最大值8388607，之后的event事件都无法写入db
#411
=> event表id字段类型mediumint=>int

modules/graph/api/graph.go
查询COUNTER类型数据时，当内存中数据的时间戳不连续时，计算出断点之后的COUNTER数据为NaN，计算错误。
例如：时间序列为（1，2，3，4，6，7，8，9），第4秒以及之后的COUNTER型数据计算值为NaN。
=> 查询COUNTER类型数据时，当内存中数据的时间戳不连续时，计算出断点之后的COUNTER数据为NaN，计算错误。

modules/hbs/db/strategy.go
fix:查询策略时候会漏掉设定的run_end时刻如23:59,导致报警策略继承关系丢失
=> fix:查询策略时候会漏掉设定的run_end时刻如23:59,导致报警策略继承关系丢失

docker/README.md
Hi, I just follow the instruction and do the docker installation today.
Then I found there's a little typo here.
=> Fix wrong docker image name in docker/readme

modules/agent/funcs/du.go
See https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables.
=> Fix loop variable captured by func literal

modules/api/app/controller/host/host_routes.go, modules/api/app/controller/host/hostgroup_controller.go
fix typo from 'APICrateHostGroup' to 'APICreateHostGroup'
=> fix typo from 'APICrateHostGroup' to 'APICreateHostGroup'

docs/_posts/Aggreator/2017-01-01-aggreator_create.md, docs/_posts/Strategy/2017-01-01-strategy_create.md, modules/api/app/controller/strategy/strategy_controller.go
According to the route definition, the url to `aggregator` creation should be `/api/v1/aggregator`
```go
//aggreator
hostr.GET("/hostgroup/:host_group/aggregators", GetAggregatorListOfGrp)
hostr.GET("/aggregator/:id", GetAggregator)
hostr.POST("/aggregator", CreateAggregator)
hostr.PUT("/aggregator", UpdateAggregator)
hostr.DELETE("/aggregator/:id", DeleteAggregator)
```
=> correct api url of 'aggregator' creation

docs/_posts/Admin/2017-12-07-admin_login.md, docs/doc/admin.html, docs/doc/admin.html.json, modules/api/app/controller/uic/session_controller.go, modules/api/app/controller/uic/user_routes.go
增加了一个 AdminLogin 的 API
以支持 dashboard 上的的第三方认证。（即 API 直接信任 dashboard 第三方认证的结果）
通过 Apitoken 授权，需要用至少管理员以上的账号起请求 Apitoken
如果请求认证的账号的也是管理员账号，则用于获取 Apitoken 的账号需要是 root
顺带把 no such user 的判断条件改为了
```
case user.ID == 0:
```
因为之前已经声明过了
```
user := uic.User{
Name: name,
}
```
所以通过 `user.Name == ""` 不可能命中条件的
=> Add AdminLogin API

modules/api/app/controller/uic/user_controller.go
目前存在即使查询数据库的返回数据为空，函数最终也判断为true的Bug。通过判断返回数据长度来解决该Bug。
=> Update user_controller.go ，解决Bug

modules/graph/http/http.go, modules/graph/main.go
**Command**: 
*./graph/bin/falcon-graph -c ./graph/config/cfg.json -v*
**Output**:
```bash
2018/09/15 11:22:35 debug.go:45: [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:   export GIN_MODE=release
- using code:  gin.SetMode(gin.ReleaseMode)
2018/09/15 11:22:35 debug.go:45: [GIN-debug] GET    /health                   --> github.com/open-falcon/falcon-plus/modules/graph/http.configCommonRoutes.func1 (3 handlers)
2018/09/15 11:22:35 debug.go:45: [GIN-debug] GET    /api/v2/health            --> github.com/open-falcon/falcon-plus/modules/graph/http.configCommonRoutes.func2 (3 handlers)
2018/09/15 11:22:35 debug.go:45: [GIN-debug] GET    /api/v2/version           --> github.com/open-falcon/falcon-plus/modules/graph/http.configCommonRoutes.fun …
```
=> fix: remove gin debug message on release mode

modules/hbs/cache/agents.go
原来只在AgentVersion，IP, PluginVersion 变化时，才做缓存更新,
这样一个问题的是没有准确记录agent 的心跳时间，从而导致基于lastUpdate
的一些判断没有意义, 比如DeleteStaleAgents 或者基于lasteUpdate
实现的agent.alive 存活状态就无法实现
=> 修改agent 缓存的lastUpdate 更新策略

modules/aggregator/sdk/sdk.go
Ignore the maintained hostname
某些服务器因为故障原因会进行维护，而进行维护的节点不运行业务，因此不需要将该服务器纳入集群视角。
=> [aggregator] Ignore the maintained hostname

modules/graph/api/graph.go
If `cfg.Debug` is true, the `InitLog` function would set log level to debug,
so debug level logging should use `logrus.Debugf`.
=> Replace custom debug log with logrus.Debugf

modules/agent/funcs/meminfo.go
修正在centos等版本下对内存计算存在较大偏差的问题：
1、第三方库在计算memfree时未考虑由于版本问题MemAvailable字段是否会计算，例如在centos6.3内存字段中就没有MemAvailable，而在cent0s7以上版本为了更好的衡量进程间通信，加入了MemAvailable字段
2、该修改在centos、ubuntu等测试均与实际值一致
=> fix agent funcs calculate meminfo problem

docs/_posts/User/2019-04-14-update-specific-user.md, modules/api/app/controller/uic/user_controller.go, modules/api/app/controller/uic/user_routes.go
Existing User update API endpoint `http://open-falcon.org/falcon-plus/#/user_update` is used to update info of login user. But in our integration development basing on Open Falcon Restful APIs, We found the need to have an endpoint to update info of users other than the login one.
Hope this endpoint is also useful to other users of open falcon
=> add API endpoint to update info of specific user

modules/api/app/controller/alarm/alarm_events_controller.go, modules/api/app/controller/alarm/alarm_notes_controller.go, modules/api/app/controller/expression/expression_controller.go, modules/api/app/controller/graph/grafana_controller.go, modules/api/app/controller/graph/graph_controller.go, modules/api/app/controller/host/aggreator_controller.go, modules/api/app/controller/host/host_controller.go, modules/api/app/controller/host/hostgroup_controller.go, modules/api/app/controller/host/plugins_controller.go, modules/api/app/controller/mockcfg/mockcfg_controller.go, modules/api/app/controller/strategy/strategy_controller.go, modules/api/app/controller/template/template_controller.go, modules/api/app/controller/uic/team_controller.go, modules/api/app/controller/uic/user_controller.go, modules/api/app/model/falcon_portal/host.go, modules/api/app/model/uic/team.go, modules/api/app/utils/set.go
fix sql injection in ctrl module
=> fix sql injection in api module

modules/alarm/g/redis.go, modules/judge/g/redis.go
pr: https://github.com/open-falcon/falcon-plus/pull/734 中`formatRedisAddr`方法有问题，没有考虑到redis密码包含`@`字符的情况
如果配置文件中redis的配置是`hello@world@127.0.0.1`(密码为`hello@world`，redis地址是`127.0.0.1`，密码包含`@`字符), 那么老的方法取到的redis密码是`hello`, redis的地址是`world`,实际上这样取到的值是完全错误的，这种情况下judge和alarm都不能正常工作
@laiwei
=> fix formatRedisAddr function bug: when password has separator character

modules/aggregator/cron/worker.go
Aggregator reports about 80 tasks "i/o timeout" , when cluster tasks more then 500, and CPU momentary value >180% . By pacing workers starting, solved this problem and CPU momentary value < 20%.
submit link: aggregator: pacing workers starting #806
=> aggregator: pacing workers starting.

cmd/monitor.go
Using command `open-falcon monitor`, and it's output as
follows:
```
...
expect logfile:
agent/config/cfg.json
```
Expected:
```
...
expect logfile:
agent/logs/agent.log
```
=> fix(monitor): incorrect path to log file

common/backend_pool/tsdb_backends.go
TsdbClient 由于要放进连接池，需要实现 NConn 接口；而 NConn 接口中的 Name() Closed() 和 io.Closer 中的 Close() 等 method signature 的 receiver 都不是指针。
秉持不修改接口的原则，这里我尝试把 cli 的 net.Conn 封装到一个结构体里面，cli本身使用指针，实现在基础类型 receiver 里修改 struct 内的 field。
=> fix issue #832

modules/gateway/receiver/rpc/rpc.go, modules/gateway/receiver/socket/socket.go, modules/graph/api/rpc.go, modules/transfer/receiver/rpc/rpc.go, modules/transfer/receiver/socket/socket.go
修复因为 rcp server  没有开启 keepalive 导致大量 ESTABLISHED 连接没法自动关闭，从而新的请求超时的问题。https://github.com/open-falcon/falcon-plus/issues/630
问题排查过程参考：https://hansedong.github.io/2018/11/16/8/
=> fix: rpc server enable keepalive

modules/agent/cfg.example.json
`ens` prefix is used for PCI Express network interface. Since it has been common, I suggest to add it as default in agent's sample config.
=> Add `ens` ifacePrefix in cfg.json.example

docker/mysql-init/Dockerfile, docker/mysql-init/init_mysql_data.sh
issue:
https://github.com/open-falcon/falcon-plus/issues/857
docker或kubernetes部署，mysql初始化应该用容器方式进行。
=> mysql初始化通过容器进行

cmd/start.go
问题复现代码
```go
package main
import (
"fmt"
"time"
)
var b bool
func main() {
go setB()
test()
}
func setB() {
time.AfterFunc(10*time.Second, func() {
fmt.Println("set true")
b = true
})
}
func test() bool {
ticker := time.NewTicker(time.Millisecond * 100)
defer ticker.Stop()
//timeout := time.After(time.Second)
for {
select {
case <-ticker.C:
if IsRunning() {
return true
}
case <-time.After(time.Second):
fmt.Println("timeout")
return false
}
}
}
func IsRunning() bool {
//<-time.After(2 * time.Second)
return b
}
```
=> 修复 cmd/start.go isStarted() 函数超时判断无用BUG。

.gitignore, docker/k8s-cluster/Dockerfile.tpl, docker/k8s-cluster/README.md, docker/k8s-cluster/build.sh, docker/k8s-cluster/init.sh, docker/k8s-cluster/modules/falcon-agent.yaml, docker/k8s-cluster/modules/falcon-aggregator.yaml, docker/k8s-cluster/modules/falcon-alarm.yaml, docker/k8s-cluster/modules/falcon-api.yaml, docker/k8s-cluster/modules/falcon-dashboard.yaml, docker/k8s-cluster/modules/falcon-graph-01.yaml, docker/k8s-cluster/modules/falcon-hbs.yaml, docker/k8s-cluster/modules/falcon-judge.yaml, docker/k8s-cluster/modules/falcon-nodata.yaml, docker/k8s-cluster/modules/falcon-transfer.yaml
现有仓库中的 [k8s-example](https://github.com/open-falcon/falcon-plus/tree/master/docker/k8s-example) 本质上是单机部署，我提供了一个利用 k8s 分布式部署例子。
=> 增加 k8s 集群部署方式

Makefile
删除源路径结尾的 /
```
work@work-hp:~/open-falcon$ /bin/ls -lF
total 71388
drwxr-xr-x 7 work work     4096 May 30  2019 agent/
drwxr-xr-x 5 work work     4096 May 30  2019 aggregator/
drwxr-xr-x 5 work work     4096 May 30  2019 alarm/
drwxr-xr-x 6 work work     4096 May 30  2019 api/
drwxr-xr-x 5 work work     4096 May 30  2019 gateway/
drwxr-xr-x 6 work work     4096 May 30  2019 graph/
drwxr-xr-x 5 work work     4096 May 30  2019 hbs/
drwxr-xr-x 5 work work     4096 May 30  2019 judge/
drwxr-xr-x 5 work work     4096 May 30  2019 nodata/
-rwxr-xr-x 1 work work  4370880 May 30  2019 open-falcon*
-rw-rw-r-- 1 work work 68685265 Nov 26 14:37 open-falcon-v0.3.tar.gz
lrwxrwxrwx 1 work work       15 May 30  2019 plugin -> ./agent/plugin//
lrwxrwxrwx 1 work work       15 May 30  2019 public -> …
```
=> Delete the end of the src path /  in ln -s cmd
